service: serverless-framework-node
provider:
  name: azure
  region: Canada Central
  runtime: nodejs18
plugins:
  - serverless-azure-functions
  - serverless-express
package:
  exclude:
    - local.settings.json
    - host.json
functions:
  api:
    handler: handler.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          route: "{*segments}"
          methods:
            - GET
            - POST
            - PUT
            - DELETE